config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('services.urls', namespace='services')),
                  path('health/', include('health.urls', namespace='health')),
                  path('users/', include('users.urls', namespace='users')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

health/urls.py
from django.urls import path, include

from health.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    RecordListView, RecordCreateView, RecordUpdateView, RecordDeleteView, RecordDetailView, DiagnosticsListView
from health.apps import HealthConfig

app_name = HealthConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_form'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('record/', RecordListView.as_view(), name='record_list'),
    path('record/<int:pk>', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', RecordCreateView.as_view(), name='record_form'),
    path('record/<int:pk>/update/', RecordUpdateView.as_view(), name='record_update'),
    path('record/<int:pk>/delete/', RecordDeleteView.as_view(), name='record_confirm_delete'),
    path('diagnostics/', DiagnosticsListView.as_view(), name='diagnostics_list'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, ResetPassword

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:verification_code>/', email_verification, name='email-confirm'),
    path('reset/', ResetPassword.as_view(), name='reset'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

health/models.py
from django.db import models

from doctor.models import Doctor
from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    name = models.CharField(max_length=100, verbose_name='Имя')
    patronymic = models.CharField(max_length=100, verbose_name='Отчество', **NULLABLE)
    surname = models.CharField(max_length=100, verbose_name='Фамилия')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.CharField(max_length=200, verbose_name='Адрес')
    email = models.EmailField(verbose_name='Почта')
    birth_date = models.DateField(verbose_name='Дата рождения')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    owner = models.ForeignKey(User, default=True, on_delete=models.CASCADE, verbose_name='пользователь')

    def __str__(self):
        return f'{self.surname} {self.name} {self.patronymic}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ['-created_at']


class Record(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    record_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата записи')
    record_time = models.TimeField(verbose_name='Время записи')
    doctor = models.ForeignKey(Doctor, max_length=100, on_delete=models.CASCADE, verbose_name='Доктор')
    owner = models.ForeignKey(User, default=True, on_delete=models.CASCADE, verbose_name='Пользователь')
    publication = models.BooleanField(default=True, verbose_name="Признак публикации")

    def __str__(self):
        return (f'{self.client.surname} {self.client.name} {self.client.patronymic} - '
                f'Вы записаны к {self.doctor} на {self.record_date} в {self.record_time}')

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'
        permissions = [
            ('can_add_record', 'Может добавлять запись'),
            ('can_change_record', 'Может изменять запись'),
            ('can_view_record', 'Может просматривать запись'),
            ('can_delete_record', 'Может удалять запись'),
        ]


class Diagnostics(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Клиент')
    diagnosis = models.CharField(max_length=300, verbose_name='Диагноз')
    test = models.CharField(max_length=200, verbose_name='Тест')
    result = models.CharField(max_length=150, verbose_name='Результат')
    units_of_measurement = models.CharField(max_length=100, verbose_name='Единицы измерения')
    proper_values = models.CharField(max_length=100, verbose_name='Должные значения')

    def __str__(self):
        return f'{self.client.surname} {self.client.name} {self.client.patronymic} - ' \
               f'Тест: {self.test}, Результат: {self.result}, Единицы измерения: {self.units_of_measurement}' \
               f'Должные значения: {self.proper_values}, Диагноз: {self.diagnosis}'

    class Meta:
        verbose_name = 'диагностика'
        verbose_name_plural = 'диагностики'
        permissions = [
            ('can_view_diagnostics', 'Может просматривать диагностики'),
        ]

health/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm

from health.models import Client, Record


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = ('name', 'surname', 'phone', 'address', 'email', 'birth_date', 'created_at')


class RecordForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Record
        fields = ('client', 'record_date', 'record_time', 'doctor')

health/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from health.models import Client, Record, Diagnostics


class ClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Client
    fields = ['name', 'surname', 'phone', 'address', 'email', 'birth_date', 'created_at']
    template_name = 'health/client_list.html'
    permission_required = 'health.view_client'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    success_url = reverse_lazy('health/client_list')

    def get_queryset(self):
        return Client.objects.all()


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = 'health/client_detail.html'
    success_url = reverse_lazy('health:client_list.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.name
        return context

    def get_queryset(self):
        return Client.objects.filter(id=self.kwargs['pk'])


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Client
    fields = '__all__'
    template_name = 'health/client_form.html'
    success_url = reverse_lazy('health:client_list.html')
    permission_required = 'health.add_client'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание клиента'
        return context

    def form_valid(self, form):
        client = form.save()
        user = self.request.user
        client.owner = user
        client.save()
        return super().form_valid(form)

    def get_queryset(self):
        return Client.objects.all()


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Client,
    fields = '__all__'
    template_name = 'health/client_form.html'
    success_url = reverse_lazy('health:client_list.html')
    permission_required = 'health.change_client'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.name
        return context

    def get_queryset(self):
        return Client.objects.filter(id=self.kwargs['pk'])


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'health/client_confirm_delete.html'
    success_url = reverse_lazy('health:client_list.html')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        client_item = self.get_object()
        context['title'] = client_item.name
        return context


class RecordListView(ListView):
    model = Record
    fields = '__all__'
    template_name = 'health/record_list.html'
    success_url = reverse_lazy('health:record_list')
    permission_required = 'health.view_record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Записи клиента'
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication=True)
        return queryset


class RecordCreateView(CreateView):
    model = Record
    fields = '__all__'
    template_name = 'health/record_form.html'
    success_url = reverse_lazy('health:record_list')
    permission_required = 'health.add_record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Создание записи для клиента'
        return context

    def get_queryset(self):
        return Record.objects.all()


class RecordDetailView(DetailView):
    model = Record
    template_name = 'health/record_detail.html'
    success_url = reverse_lazy('health:record_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        record_item = self.get_object()
        context['title'] = f'Запись клиента {record_item.client.name} {record_item.client.surname}'
        return context

    def get_queryset(self):
        return Record.objects.filter(id=self.kwargs['pk'])


class RecordUpdateView(UpdateView):
    model = Record
    fields = '__all__'
    template_name = 'health/record_form.html'
    success_url = reverse_lazy('health:record_list')
    permission_required = 'health.change_record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        record_item = self.get_object()
        context['title'] = f'Редактирование записи клиента {record_item.client.name} {record_item.client.surname}'
        return context


class RecordDeleteView(DeleteView):
    model = Record
    template_name = 'health/record_confirm_delete.html'
    success_url = reverse_lazy('health:record_list')
    permission_required = 'health.delete_record'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        record_item = self.get_object()
        context['title'] = f'Удаление записи клиента {record_item.client.name} {record_item.client.surname}'
        return context


class DiagnosticsListView(ListView):
    model = Diagnostics
    fields = '__all__'
    template_name = 'health/diagnostics_list.html'
    success_url = reverse_lazy('services:service_list')
    permission_required = 'health.view_diagnostics'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Лечебные консультации'
        return context

health/templates/health/client_confirm_delete.html
{% extends 'services/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-8">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <p> Хотите удалить запись? </p>
                                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>

                                        </form>
                                        <a href="{% url 'health:client_list' %}" class="btn btn-lg btn-block btn-outline-primary">Отмена</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

health/templates/health/client_ditail.html
{% extends 'services/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.first_name|title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col">
                    <p class="card shadow-sm">
                        <img class="card-img-top" src="{{ object.emile }}" alt="Фотографии нет">
                    </p>
                </div>
                <div class="col-5 text-md-start">
                    {{ object.comment|truncatechars:20 }}
                    <p>
                        <a href="{% url 'service:client_list' %}"
                           class="btn btn-primary justify-content-md-center my-5">Клиент созданный, {{object.owner}} $</a>
                    </p>
                </div>
            </div>

        </div>
    </div>
</main>

{% endblock %}

health/templates/health/client_form.html
{% extends 'service/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">{{ object.first_name|title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-12">
                    <div class="row">
                        <div class="col-8">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        {% if object %}
                                        <button type="submit" class="btn btn-primary">Изменить</button>
                                        {% else %}
                                        <button type="submit" class="btn btn-primary">Сохранить</button>
                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

health/templates/health/client_list.html
{% extends 'services/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-3 pb-md-3 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
</div>
<form method="post" action="" class="form-floating">
    {% csrf_token %}
        <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                                    href="{% url 'health:client_form' %}">
                                    Добавить запись</a>
    <div class="row">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for object in object_list|slice:5 %}
            <div class="col-4">
                <div class="card mb-6 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">
                            {{object.email}}</h4>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title"> {{object.first_name}}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                            </ul>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'health:client_detail' object.pk %}">
                                Подробнее
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'health:client_update' object.pk %}">
                                Изменить
                            </a>
                            <a type="button" class="btn btn-lg btn-block btn-outline-primary"
                               href="{% url 'health:client_confirm__delete' object.pk %}">
                                Удалить
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</form>
{% endblock %}

health/templates/health/diagnostics_list.html
{% extends 'services/base.html' %}
{% block content %}
<body>
<div class="card border-warning mb-3" style="max-width: 18rem;">
    {% for object in object_list %}
    <div class="card-header">Данные клиента</div>
    <div class="card-body">
        <h5 class="card-title">{{ object.client }}</h5>
        <p class="card-text">Дата рождения: {{ object.client.birth_date }} </p>
        <p class="card-text">Пол: </p>
        <p class="card-text">Возраст: </p>
        <p class="card-text">Адрес: {{ object.client.address }} </p>
    </div>
    {% endfor %}
</div>
<div class="card border-primary mb-3" style="max-width: 18rem;">
    {% for object in object_list %}
    <div class="card-header">Тест</div>
    <div class="card-body text-primary">
        <h5 class="card-title">{{ object.test }} </h5>
        <p class="card-text"></p>
    </div>
    {% endfor %}
</div>
<div class="card border-secondary mb-3" style="max-width: 18rem;">
    {% for object in object_list %}
    <div class="card-header">Ед. измерения</div>
    <div class="card-body text-secondary">
        <h5 class="card-title"> {{ object.units_of_measurement }} </h5>
        <p class="card-text"></p>
    </div>
    {% endfor %}
</div>
<div class="card border-success mb-3" style="max-width: 18rem;">
    {% for object in object_list %}
    <div class="card-header">Должные значения</div>
    <div class="card-body text-success">
        <h5 class="card-title">{{ object.proper_values }}</h5>
        <p class="card-text"></p>
    </div>
    {% endfor %}
</div>
<div class="card border-danger mb-3" style="max-width: 18rem;">
    {% for object in object_list %}
    <div class="card-header">Результат</div>
    <div class="card-body text-danger">
        <h5 class="card-title">{{ object.result }}</h5>
        <p class="card-text"></p>
    </div>
    <div class="card-header">Диагноз</div>
    <div class="card-body">
        <h5 class="card-title">{{ object.diagnosis }}</h5>
        <p class="card-text"></p>
    </div>
    {% endfor %}
</div>
{% endblock %}
</div>

</body>

health/templates/health/record_confirm_delete.html
{% extends 'services/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-12">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <p> Хотите удалить запись? </p>
                                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>

                                        </form>
                                        <a href="{% url 'health:record_list' %}" class="btn btn-lg btn-block btn-outline-primary">Отмена</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

health/templates/health/record_detail.html
{% extends 'services/base.html' %}
{% load my_tags_health %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-6">
        {{ object.client }}</h1>
    <h1 class="display-6">Записан(а) на прием ко врачу {{ object.doctor }}</h1>
    <h1 class="display-6">на {{ object.record_date }} </h1>
 </div>
{% endblock %}

health/templates/health/record_form.html
{% extends 'services/base.html' %}
{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

health/templates/health/record_list.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'health:record_form' %}">Добавить запись</a>
    </div>
    {% for object in object_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">
                        {{ object.client }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'health:record_detail' object.pk %}"
                               class="btn btn-sm btn-outline-primary">Подробнее</a>
                            <a href="{% url 'health:record_update' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Изменить</a>
                            <a href="{% url 'health:record_confirm_delete' object.pk %}" type="button"
                               class="btn btn-sm btn-outline-primary">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}