config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('services.urls', namespace='services')),
                  path('health/', include('health.urls', namespace='health')),
                  path('users/', include('users.urls', namespace='users')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from doctor.apps import DoctorConfig
from doctor.views import DoctorListView, DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView, \
    OurDoctorView

app_name = DoctorConfig.name

urlpatterns = [
    path('', DoctorListView.as_view(), name='doctor_list'),
    path('our_doctors/', cache_page(60)(OurDoctorView.as_view()), name='our_doctors'),
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_form'),
    path('doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/<int:pk>/update/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/<int:pk>/delete/', DoctorDeleteView.as_view(), name='doctor_confirm_delete'),
]

health/urls.py
from django.urls import path, include

from health.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    RecordListView, RecordCreateView, RecordUpdateView, RecordDeleteView, RecordDetailView, DiagnosticsListView
from health.apps import HealthConfig

app_name = HealthConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_form'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('record/', RecordListView.as_view(), name='record_list'),
    path('record/<int:pk>', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', RecordCreateView.as_view(), name='record_form'),
    path('record/<int:pk>/update/', RecordUpdateView.as_view(), name='record_update'),
    path('record/<int:pk>/delete/', RecordDeleteView.as_view(), name='record_confirm_delete'),
    path('diagnostics/', DiagnosticsListView.as_view(), name='diagnostics_list'),

]

services/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from services.apps import ServiceConfig
from services.views import ServiceCreateView, ServiceDetailView, ServiceUpdateView, ServiceDeleteView, \
    ContactView, ServiceListView, FeedbackView, SitemapView

app_name = ServiceConfig.name

urlpatterns = [
    path('', ServiceListView.as_view(), name='service_list'),
    path('services/', ServiceListView.as_view(), name='service_main'),
    path('services/create/', ServiceCreateView.as_view(), name='service_form'),
    path('services/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('services/<int:pk>/update/', ServiceUpdateView.as_view(), name='service_update'),
    path('services/<int:pk>/delete/', ServiceDeleteView.as_view(), name='service_confirm_delete'),
    path('contact/', ContactView.as_view(), name="contact_list"),
    path('feedback/', FeedbackView.as_view(), name="feedback_list"),
    path('site_map/', SitemapView.as_view(), name="site_map_list"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, ResetPassword

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:verification_code>/', email_verification, name='email-confirm'),
    path('reset/', ResetPassword.as_view(), name='reset'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

doctor/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Doctor(models.Model):
    avatar = models.ImageField(upload_to='doctor/', **NULLABLE)
    name = models.CharField(max_length=255, verbose_name='Имя доктора')
    patronymic = models.CharField(max_length=255, verbose_name='Отчество доктора', **NULLABLE)
    surname = models.CharField(max_length=255, verbose_name='Фамилия доктора')
    age = models.PositiveIntegerField(verbose_name='Возраст', **NULLABLE)
    specialization = models.CharField(max_length=255, verbose_name='Специализация')
    qualification = models.CharField(max_length=255, verbose_name='Квалификация')
    experience = models.PositiveIntegerField(verbose_name='Опыт работы в летах')

    def __str__(self):
        return f'{self.name} {self.patronymic} {self.surname}, {self.specialization}, {self.qualification}'

    class Meta:
        verbose_name = 'доктор'
        verbose_name_plural = 'доктора'

doctor/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm

from doctor.models import Doctor


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class DoctorForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Doctor
        fields = ('name', 'surname', 'specialization', 'qualification', 'experience')

doctor/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from doctor.models import Doctor


class DoctorListView(ListView):
    model = Doctor
    fields = ['name', 'patronymic', 'surname', 'specialization', 'qualification']
    template_name = 'doctor/doctor_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    success_url = reverse_lazy('doctor: doctor_list')

    def get_template_names(self):
        if self.request.path == '/doctor/':
            return ['doctor/our_doctors.html']
        elif self.request.path == '/':
            return ['doctor/doctor_list.html']


class DoctorCreateView(CreateView):
    model = Doctor
    fields = ['name', 'patronymic', 'surname','specialization', 'qualification']
    template_name = 'doctor/doctor_form.html'
    success_url = reverse_lazy('doctor:doctor_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def get_queryset(self, *args, **kwargs):
        queryset =Doctor.objects.all(*args, **kwargs)
        return queryset


class DoctorDetailView(DetailView):
    model = Doctor
    template_name = 'doctor/doctor_detail.html'


class DoctorUpdateView(UpdateView):
    model = Doctor
    fields = ['name', 'patronymic', 'surname','specialization', 'qualification']
    template_name = 'doctor/doctor_form.html'
    success_url = reverse_lazy('doctor:doctor_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DoctorDeleteView(DeleteView):
    model = Doctor
    template_name = 'doctor/doctor_confirm_delete.html'
    success_url = reverse_lazy('doctor:doctor_list')


class OurDoctorView(ListView):
    model = Doctor
    template_name = 'doctor/our_doctor.html'

doctor/templates/doctor/doctor_confirm_delete.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">



    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Удалить данные</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-6">
                    <div class="row">
                        <div class="col-8">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <p> Хотите удалить данные по врачу? </p>
                                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                                            Подтвердить</button>
                                        </form>
                                        <a href="{% url 'services:service_list' %}"
                                           class="btn btn-lg btn-block btn-outline-primary">Отмена</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
</body>
</html>

doctor/templates/doctor/doctor_detail.html
{% load static %}
{% load my_tags_doctor %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>
<section class="pb-5">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <a class="p-2 btn btn-primary" href="{% url 'services:service_list' %}">Главная</a>
                <a class="p-2 btn btn-primary" href="{% url 'users:login' %}">Личный кабинет</a>
            </div>
        </div>
    </div>
</section>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                   <svg class="bd- aceholder-img card-img-top" width="100%" height="15"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label=""
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <img class="card-img-top" src="/media/{{ object.avatar }}" alt="Фото врача">
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em"></text>
                    </svg>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object.name|title }}</h1>
    <h1 class="display-4">{{ object.patronymic }}</h1>
    <h1 class="display-4">{{ object.surname }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-5 text-md-start">
                    <h1 class="lead mb-6">
                        Направление: {{ object.specialization }}
                        <h1 class="lead mb-6">
                            Должность: {{ object.qualification }}
                            <h1 class="lead mb-6">
                                Стаж работы: {{ object.experience }} лет
                            </h1>
                            <p>
                                <a href="{% url 'services:service_main' %}"
                                   class="btn btn-primary justify-content-md-center my-5">
                                    Первичная консультация врача
                                </a>
                            </p>
                </div>
            </div>
        </div>
    </div>
</main>
</body>
</html>

doctor/templates/doctor/doctor_form.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">



    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>
<html lang="en" data-bs-theme="auto">
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">Изменить или добавить данные</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                <div class="col-10">
                    <div class="row">
                        <div class="col-6">
                            <div class="card">
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        {{ form.as_p }}
                                        {% if object %}
                                        <button type="submit" class="btn btn-primary">Изменить</button>
                                        {% else %}
                                        <button type="submit" class="btn btn-primary">Сохранить</button>
                                        {% endif %}
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
</html>
</body>

doctor/templates/doctor/our_doctors.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
<meta name="generator" content="Hugo 0.122.0">


<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" crossorigin="anonymous">


<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
      z-index: 1500;
    }

    .bd-mode-toggle .dropdown-menu .active .bi {
      display: block !important;
    }
</style>


<!-- Custom styles for this template -->
<link href="{% static 'heroes.css' %}" rel="stylesheet">
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>
<div class="navbar navbar-dark  box-shadow" style="background-image: url(/media/healthcare-background-svbgqjgz7j1fx9p1.jpg)">
    <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                 stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                <circle cx="12" cy="13" r="4"></circle>
            </svg>
            <strong>Медицинский центр - Здоровье</strong>
        </a>

    </div>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'services:service_list' %}">Главная</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'doctor:our_doctors' %}">О компании</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'services:service_main' %}">Наши
                    услуги</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'doctor:doctor_list' %}">Наши врачи</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'services:contact_list' %}">Контакты</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'services:feedback_list' %}">Обратная
                    связь</a>
                {% if not user.is_authenticated %}
                <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Личный кабинет</a>
                {% endif %}
            </div>
        </nav>
    </div>
</div>
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">

                <a href="{% url 'health:record_list' %}" class="p-2 btn btn-outline-primary">Просмотр записи на
                    прием</a>
                <a href="{% url 'health:diagnostics_list' %}" class="p-2 btn btn-outline-primary">Результаты
                    диагностики</a>
            </div>
        </div>
    </div>
    <div class="px-4 pt-5 my-5 text-center border-bottom">
        <h1 class="display-5 fw-bold text-body-emphasis">Наши врачи</h1>
        {% if user.is_superuser %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <a type="button" class="btn btn-sm btn-block btn-outline-primary"
               href="{% url 'doctor:doctor_form' %}">
                Добавить запись</a>
        </div>
        {% endif %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm h-100">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="15"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                        <img src="/media/{{ object.avatar }}" class="img-thumbnail" alt="...">
                        <rect width="100%" height="100%" fill="#55595c"/>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">
                        <h1 class="display-11 fw-bold text-body-emphasis">{{ object.name }}</h1></p>
                        <p class="card-text">
                        <h1 class="display-11 fw-bold text-body-emphasis"> {{ object.patronymic }}</h1></p>
                        <p class="card-text">
                        <h1 class="display-11 fw-bold text-body-emphasis">{{ object.surname }}</h1></p>
                        <p class="card-text"> {{ object.specialization}}</p>
                        <p class="card-text"> {{ object.qualification }}</p>
                        <p class="card-text"> Стаж работы- {{ object.experience }} лет</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a class="btn btn-sm btn-outline-primary"
                                           href="{% url 'doctor:doctor_detail' object.pk %}">Подробнее</a>
                                        {% if perms.doctor.change_doctor %}
                                        <a class="btn btn-sm btn-outline-primary"
                                           href="{% url 'doctor:doctor_update' object.pk %}">Изменить</a>
                                        {% endif %}
                                        {% if perms.doctor.delete_doctor %}
                                        <a class="btn btn-sm btn-outline-primary"
                                           href="{% url 'doctor:doctor_confirm_delete' object.pk %}">Удалить</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="b-example-divider mb-0"></div>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>

</body>
</html>