config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('services.urls', namespace='services')),
                  path('health/', include('health.urls', namespace='health')),
                  path('users/', include('users.urls', namespace='users')),
                  path('doctor/', include('doctor.urls', namespace='doctor')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctor/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from doctor.apps import DoctorConfig
from doctor.views import DoctorListView, DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView, \
    OurDoctorView

app_name = DoctorConfig.name

urlpatterns = [
    path('', DoctorListView.as_view(), name='doctor_list'),
    path('our_doctors/', cache_page(60)(OurDoctorView.as_view()), name='our_doctors'),
    path('doctor/create/', DoctorCreateView.as_view(), name='doctor_form'),
    path('doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctor/<int:pk>/update/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctor/<int:pk>/delete/', DoctorDeleteView.as_view(), name='doctor_confirm_delete'),
]

health/urls.py
from django.urls import path, include

from health.views import ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, \
    RecordListView, RecordCreateView, RecordUpdateView, RecordDeleteView, RecordDetailView, DiagnosticsListView
from health.apps import HealthConfig

app_name = HealthConfig.name

urlpatterns = [
    path('', ClientListView.as_view(), name='client_list'),
    path('client/create/', ClientCreateView.as_view(), name='client_form'),
    path('client/<int:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
    path('record/', RecordListView.as_view(), name='record_list'),
    path('record/<int:pk>', RecordDetailView.as_view(), name='record_detail'),
    path('record/create/', RecordCreateView.as_view(), name='record_form'),
    path('record/<int:pk>/update/', RecordUpdateView.as_view(), name='record_update'),
    path('record/<int:pk>/delete/', RecordDeleteView.as_view(), name='record_confirm_delete'),
    path('diagnostics/', DiagnosticsListView.as_view(), name='diagnostics_list'),

]

services/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from services.apps import ServiceConfig
from services.views import ServiceCreateView, ServiceDetailView, ServiceUpdateView, ServiceDeleteView, \
    ContactView, ServiceListView, FeedbackView, SitemapView

app_name = ServiceConfig.name

urlpatterns = [
    path('', ServiceListView.as_view(), name='service_list'),
    path('services/', ServiceListView.as_view(), name='service_main'),
    path('services/create/', ServiceCreateView.as_view(), name='service_form'),
    path('services/<int:pk>/', ServiceDetailView.as_view(), name='service_detail'),
    path('services/<int:pk>/update/', ServiceUpdateView.as_view(), name='service_update'),
    path('services/<int:pk>/delete/', ServiceDeleteView.as_view(), name='service_confirm_delete'),
    path('contact/', ContactView.as_view(), name="contact_list"),
    path('feedback/', FeedbackView.as_view(), name="feedback_list"),
    path('site_map/', SitemapView.as_view(), name="site_map_list"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, email_verification, ResetPassword

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('email-confirm/<str:verification_code>/', email_verification, name='email-confirm'),
    path('reset/', ResetPassword.as_view(), name='reset'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

services/models.py
from django.db import models

from doctor.models import Doctor

NULLABLE = {'blank': True, 'null': True}


class Service(models.Model):
    name = models.CharField(max_length=250, verbose_name='Услуга')
    description = models.TextField(max_length=250, verbose_name='Описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    picture = models.ImageField(upload_to='services/', **NULLABLE, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'
        ordering = ['name']
        permissions = [
            ('can_add_service', 'Может добавлять услугу'),
            ('can_change_service', 'Может изменять услугу'),
            ('can_view_service', 'Может просматривать услугу'),
        ]


class Contact(models.Model):
    email = models.EmailField(verbose_name='E-mail')
    phone = models.CharField(max_length=20, verbose_name='Телефон')
    address = models.CharField(max_length=250, verbose_name='Адрес')

    def __str__(self):
        return f'{self.phone} {self.address} {self.email}'

    class Meta:
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'
        ordering = ['phone']


class Sitemap(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Описание')
    travel_map = models.URLField(verbose_name='URL')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Карта сайта'
        verbose_name_plural = 'Карты сайта'

services/forms.py
from django.db.models import BooleanField
from django.forms import ModelForm

from services.models import Service, Contact, Sitemap


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ServiceForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Service
        fields = ('name', 'description', 'price')


class ContactForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Contact
        fields = ('email', 'phone', 'address')


class FeedbackForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'phone', 'content')


class SitemapForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Sitemap
        fields = ('title', 'content', 'travel_map')

services/views.py
from django.urls import reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from services.models import Service, Contact, Sitemap


class ServiceListView(ListView):
    model = Service
    fields = ['id', 'name', 'description', 'price']
    paginate_by = 10
    permission_required = 'services.view_service'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Все услуги'
        return context

    def get_template_names(self):
        if self.request.path == '/':
            return ['services/service_list.html']
        elif self.request.path == '/services/':
            return ['services/service_main.html']


class ServiceCreateView(CreateView):
    model = Service
    fields = '__all__'
    template_name = 'services/service_form.html'
    success_url = reverse_lazy('services:service_list')
    permission_required = 'services.add_service'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Создание услуги'
        return context

    def form_valid(self, form):
        return super().form_valid(form)


class ServiceDetailView(DeleteView):
    model = Service
    template_name = 'services/service_detail.html'
    success_url = reverse_lazy('services:service_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Подробнее о услуге'
        return context

    def get_queryset(self, *args, **kwargs):
        queryset = Service.objects.filter(id=self.kwargs['pk'])
        return queryset


class ServiceUpdateView(UpdateView):
    model = Service
    fields = '__all__'
    template_name = 'services/service_form.html'
    success_url = reverse_lazy('services:service_list')
    permission_required = 'services.change_service'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование услуги'
        return context

    def form_valid(self, form):
        return super().form_valid(form)

    def get_queryset(self, *args, **kwargs):
        queryset = Service.objects.all(*args, **kwargs)
        return queryset


class ServiceDeleteView(DeleteView):
    model = Service
    template_name = 'services/service_confirm_delete.html'
    success_url = reverse_lazy('services:service_list')


class ContactView(ListView):
    model = Contact
    fields = '__all__'
    template_name = 'services/contact_list.html'


class FeedbackView(ListView):
    model = Contact
    fields = '__all__'
    template_name = 'services/feedback_list.html'


class SitemapView(ListView):
    model = Sitemap
    fields = '__all__'
    template_name = 'services/site_map_list.html'

services/templates/services/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

</head>

<body>

<header style="background-image: url(/media/healthcare-background-svbgqjgz7j1fx9p1.jpg)">
    <div class="collapse" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-primary">О нас</h4>
                    <p class="text-white">Медецинский центр "ЗДОРОВЬЕ"– это мощный
                        многопрофильный лечебно-диагностический комплекс. На протяжении 30 лет центр остается ведущим
                        учреждением оказания высококвалифицированной медицинской помощи. Высокая
                        компетентность и профессионализм наших специалистов, подкрепленные обновленной
                        материально-технической базой центра, позволяют с высокой точностью проводить обследования и
                        осуществлять диагностику заболеваний в любых самых сложных случаях. В штате диагностического
                        центра кандидаты медицинских наук, врачи высшей категории, имеющие серьезный опыт работы и
                        владеющие современными методиками диагностики и лечения.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-primary">Это Вам понадобится</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'services:contact_list' %}" class="text-white">Контакты</a></li>
                        <li><a href="{% url 'services:site_map_list' %}" class="text-white">Карта сайта</a></li>
                        <li><a href="{% url 'services:feedback_list' %}" class="text-white">Обратная связь</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% include 'services/includes/inc_main.html' %}
</header>

<main role="main">
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">

                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Вернуться к началу</a>
        </p>
        <p> &copy; 2024 - {% now 'Y' %} Компания медицинской диагностики , 2024</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

services/templates/services/contact_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Медицинский центр ЗДОРОВЬЕ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
</head>
<body>

{% include 'services/includes/inc_main.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Адрес компании:</td>
                            <td>Гороховецкая 46</td>
                        </tr>
                        <tr>
                            <td class="w-25">Контактный телефон:</td>
                            <td>8920-015-22-67</td>
                        </tr>
                        <tr>
                            <td class="w-25">Email:</td>
                            <td>blev1973@mail.ru</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="container">
                <div class="row text-start">
                    <div class="col-lg-12 col-md-6 col-sm-12">
                        <div class="card mb-4 box-shadow">
                            <div class="card-body">
                                <tr>
                                    <td class="w-25">Схема проезда</td>
                                    <img class="card-img-top" src="/media/2024-08-07_14-00-53.png" alt="Схема проезда">
                                </tr>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    Медицинский центр - Здоровье
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Категории</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Рассылки</a></li>
                        <li><a class="text-muted" href="#">Телеграм боты</a></li>
                        <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                        <li><a class="text-muted" href="#">Веб-приложения</a></li>
                        <li><a class="text-muted" href="#">Микросервисы</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Дополнительно</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Мы пишем</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>О нас</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="/contacts_list/">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
</body>
</html>

services/templates/services/feedback_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Медицинский центр ЗДОРОВЬЕ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">
</head>
<body>
{% include 'services/includes/inc_main.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Обратная связь</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-8 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts_list/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

services/templates/services/service_confirm_delete.html
{% extends 'services/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-8">{{ title }}</h1>
</div>
<main>
    <div class="album py-3 bg-body-tertiary">
        <div class="container text-center">
            <div class="row row-cols-1 row-cols-sm-1 row-cols-md-2 g-3">
                    <div class="col-12">
                        <div class="row">
                            <div class="col-10">
                                <div class="card">
                                    <div class="card-body">
                                        <form method="post" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <p> Хотите удалить запись "{{ object.name }}"? </p>
                                            <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Подтвердить</button>

                                        </form>
                                        <a href="{% url 'services:service_list' %}" class="btn btn-lg btn-block btn-outline-primary">Отмена</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}

services/templates/services/service_list.html
{% extends 'services/base.html' %}

{% block content %}
<main>
    <div class="collapse" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-primary">О нас</h4>
                    <p class="text-white">
                        Медицинский центр "ЗДОРОВЬЕ" — это мощный многопрофильный лечебно-диагностический комплекс.
                        На протяжении 30 лет центр остается ведущим учреждением оказания высококвалифицированной
                        медицинской помощи. Высокая компетентность и профессионализм наших специалистов, подкрепленные
                        обновленной материально-технической базой центра, позволяют с высокой точностью проводить
                        обследования и осуществлять диагностику заболеваний в любых самых сложных случаях. В штате
                        диагностического центра кандидаты медицинских наук, врачи высшей категории, имеющие серьезный
                        опыт работы и владеющие современными методиками диагностики и лечения.
                    </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-primary">Это Вам понадобится</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'services:contact_list' %}" class="text-white">Контакты</a></li>
                        <li><a href="{% url 'services:site_map_list' %}" class="text-white">Карта сайта</a></li>
                        <li><a href="{% url 'services:feedback_list' %}" class="text-white">Обратная связь</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container my-4">
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-secondary" href="{% url 'users:profile' %}">Профиль</a>
        <a class="p-2 btn btn-secondary" href="{% url 'users:logout' %}">Выйти</a>
        <a href="{% url 'health:record_form' %}" class="btn btn-secondary my-2">Запись на прием</a>
        <a href="{% url 'health:record_list' %}" class="btn btn-secondary my-2">Просмотр записи на прием</a>
        <a href="{% url 'health:diagnostics_list' %}" class="btn btn-secondary my-2">Результаты диагностики</a>
        {% else %}
        <a class="p-2 btn btn-primary" href="{% url 'users:login' %}">Войти</a>
        <a class="p-2 btn btn-primary" href="{% url 'users:register' %}">Регистрация</a>
        <a href="{% url 'health:record_form' %}" class="btn btn-secondary my-2">Запись на прием</a>
        {% endif %}
    </div>

    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        {% include 'services/includes/inc_main_1.html' %}
        <h1 class="h3 mb-5 fw-normal">Перечень предоставляемых услуг</h1>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for object in object_list %}
            <div class="col">
                <div class="card h-100">
                    <img class="card-img-top" src="/media/{{ object.picture }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name|title }}</h5>
                        <p class="card-text">{{ object.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'services:service_detail' object.pk %}" class="btn btn-sm btn-outline-primary">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </form>
</main>
{% endblock %}

services/templates/services/service_main.html
{% extends 'services/base.html' %}
{% block content %}
<main>
    <a class="btn btn-secondary my-2" href="{% url 'health:record_list' %}" >Просмотр записи на прием</a>
    <a href="{% url 'health:diagnostics_list' %}" class="btn btn-secondary my-2">Результаты диагностики</a>
    <form method="post" action="" class="form-floating">
        {% csrf_token %}
        <div class="px-4 pt-5 my-5 text-center border-bottom">
            <h1 class="display-5 fw-bold text-body-emphasis">Перечень предоставляемых услуг</h1>
            {% if user.is_superuser %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                <a type="button" class="btn btn-sm btn-block btn-outline-primary"
                   href="{% url 'services:service_form' %}">
                    Добавить запись</a>
            </div>
            {% endif %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-4">
                {% for object in object_list %}
                <div class="col">
                    <div class="card shadow-sm h-100">
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="20"
                             xmlns="http://www.w3.org/2000/svg" role="" aria-label="Placeholder: Thumbnail"
                             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                            <img src="/media/{{ object.picture }}" class="img-thumbnail" alt="...">
                            <rect width="100%" height="100%" fill="#55595c"/>

                        </svg>
                        <div class="card-body">
                            <h1 class="display-6 fw-bold text-bdy-emphasis">{{ object.name|title }}</h1></p>
                            <p class="card-text">{{ object.description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-outline-primary"
                                               href="{% url 'services:service_detail' object.pk %}">Подробнее</a>
                                            {% if perms.services.change_service %}
                                            <a class="btn btn-sm btn-outline-primary"
                                               href="{% url 'services:service_update' object.pk %}">Изменить</a>
                                            {% endif %}
                                            {% if perms.services.delete_service %}
                                            <a class="btn btn-sm btn-outline-primary"
                                               href="{% url 'services:service_confirm_delete' object.pk %}">Удалить</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </form>
</main>
{% endblock %}

services/templates/services/site_map_list.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Медицинский центр ЗДОРОВЬЕ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
</head>
<body>
{% include 'services/includes/inc_main.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <h1 class="display-4">Карта сайта</h1>
    <ul class="nav nav-underline">
        <li class="nav-item">
            <nav class="nav flex-column">
                <a class="nav-link active" aria-current="page" href="{% url 'services:service_list' %}">* Главная</a>
                <a class="nav-link" aria-current="page" href="{% url 'doctor:our_doctors' %}">* О компании</a>
                <a class="nav-link" aria-current="page" href="{% url 'doctor:doctor_list' %}">* Наши врачи</a>
                <a class="nav-link" aria-current="page" href="{% url 'services:service_main' %}">* Наши услуги</a>
                <a class="nav-link " aria-current="page" href="{% url 'users:login' %}">* Личный кабинет</a>
                <a class="nav-link " aria-current="page" href="{% url 'health:record_list' %}">* Запись на прием</a>
                <a class="nav-link " aria-current="page" href="{% url 'health:diagnostics_list' %}">* Диагностика</a>
                <a class="nav-link " aria-current="page" href="#">* Отзывы</a>
                <a class="nav-link " aria-current="page" href="{% url 'services:contact_list' %}">* Контакты</a>
                <a class="nav-link " aria-current="page" href="{% url 'services:site_map_list' %}">* Карта сайта</a>
                <a class="nav-link " aria-current="page" href="{% url 'services:feedback_list' %}">* Обратная связь</a>
            </nav>
        </li>
    </ul>
</div>
</body>
</html>